version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 6666:8080
      - 6001:80
    networks:
      - backend
      - frontend
    depends_on:
      - php
      - db
    volumes:
      - ./html:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:fpm
    networks:
      - backend
    volumes:
      - ./html:/var/www/html
  db:
    image: mysql
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=BazaTestowa
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpasswd
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    networks:
      - backend
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpasswd
networks:
  backend:
  frontend:
